# Crowdin Configuration for VulkanMod Extra
# Documentation: https://support.crowdin.com/configuration-file/

# Project identifier (get this from Crowdin project settings)
project_id: "852664"

# API token from environment variable (recommended for security)
# Set this in your CI/CD: export CROWDIN_PERSONAL_TOKEN="your-token"
api_token_env: CROWDIN_PERSONAL_TOKEN

# Preserve directory hierarchy in Crowdin
preserve_hierarchy: true

# File configuration
files:
  # VulkanMod Extra language files
  - source: /common/src/main/resources/assets/vulkanmod-extra/lang/en_us.json
    translation: /common/src/main/resources/assets/vulkanmod-extra/lang/%locale%.json
    
    # Update strategy: import new strings as unapproved
    update_option: update_as_unapproved
    
    # Locale mapping (Crowdin format -> Minecraft format)
    # Crowdin uses format like "cs", "de", "pt-BR"
    # Minecraft uses format like "cs_cz", "de_de", "pt_br"
    languages_mapping:
      locale:
        cs: cs_cz
        de: de_de
        es: es_es
        fr: fr_fr
        it: it_it
        ja: ja_jp
        ko: ko_kr
        nl: nl_nl
        pl: pl_pl
        pt-BR: pt_br
        ru: ru_ru
        sv-SE: sv_se
        tr: tr_tr
        zh-CN: zh_cn
        zh-TW: zh_tw
