@echo off
setlocal enabledelayedexpansion

REM Create Override Script for VulkanMod Extra
REM Creates version-specific override directories and files

set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."

set "SUPPORTED_VERSIONS=1.21.1 1.21.2 1.21.3 1.21.4 1.21.5"

if "%~1"=="" (
    echo Usage: %~n0 ^<class_or_mixin_name^> [^<version^>]
    echo.
    echo Examples:
    echo   %~n0 MixinLevelRenderer 1.21.3
    echo   %~n0 "net.vulkanmod.extra.config.Config" 1.21.3
    echo.
    echo If version is not specified, uses current version from gradle.properties
    exit /b 1
)

set "class_name=%~1"
set "version=%~2"

REM Determine target version
if "%version%"=="" (
    REM Get current version from gradle.properties
    for /f "tokens=2 delims==" %%v in ('findstr "minecraft_version" "%PROJECT_DIR%\gradle.properties"') do set "version=%%v"
)

REM Check if version is supported
set "version_supported=0"
for %%v in (%SUPPORTED_VERSIONS%) do (
    if "%%v"=="%version%" set "version_supported=1"
)

if !version_supported! equ 0 (
    echo Error: Unsupported version: %version%
    echo Supported versions: %SUPPORTED_VERSIONS%
    exit /b 1
)

set "version_key=%version:.=_%"
set "override_dir=%PROJECT_DIR%\src\overrides\v%version_key%"

REM Create override directory structure
if not exist "%override_dir%" mkdir "%override_dir%"
if not exist "%override_dir%\java" mkdir "%override_dir%\java"
if not exist "%override_dir%\resources" mkdir "%override_dir%\resources"

REM Extract class name components
set "simple_name=%class_name%"
for /f "tokens=1* delims=." %%a in ("%class_name%") do set "simple_name=%%b"
if "%%a" neq "" set "simple_name=%%b"

REM Determine if this is a mixin class
set "is_mixin=0"
echo %class_name% | findstr /i "Mixin" >nul 2>&1
if !errorlevel! equ 0 set "is_mixin=1"

REM Create override file based on class type
if %is_mixin% equ 1 (
    REM Create mixin override
    set "mixin_dir=%override_dir%\java"
    set "package_path=%class_name:.=\%"
    set "package_dir=%package_path:\Mixin\=\\Mixin\%"
    
    set "target_file=%override_dir%\java\%package_path%"
    
    if not exist "!target_file!" (
        echo Creating mixin override: !target_file!
        
        REM Create package directories
        for %%d in ("!package_dir:\=" "!") do (
            if not exist "%override_dir%\java\%%~d" mkdir "%override_dir%\java\%%~d"
        )
        
        REM Copy existing file if it exists
        if exist "%PROJECT_DIR%\src\main\java\%package_path%" (
            copy "%PROJECT_DIR%\src\main\java\%package_path%" "!target_file!"
            echo Copied existing file to override location
        ) else (
            echo @echo off
            echo.
            echoREM Override mixin for %version%
            echoREM Auto-generated by create-override.bat
            echoREM Target version: %version%
            echo.
            echopackage %class_name:*.=%
            echo.
            echoimport org.spongepowered.asm.mixin.Mixin;
            echo.
            REM Extract target class from mixin name (remove "Mixin" prefix)
            set "target_class=%class_name:Mixin=%"
            set "target_class=%target_class:~0,-1%"
            echo^@Mixin(%target_class%)
            echopublic class %simple_name% {
            echo    
            echo    ^// Version-specific mixin implementation for Minecraft %version%
            echo    ^// Override the base mixin with version-specific fixes
            echo    
            echo}
            echo. > "!target_file!"
        )
    ) else (
        echo Override file already exists: !target_file!
    )
) else (
    REM Create regular Java class override
    set "class_dir=%override_dir%\java"
    set "package_path=%class_name:.=\%"
    
    set "target_file=%override_dir%\java\%package_path%"
    
    if not exist "!target_file!" (
        echo Creating class override: !target_file!
        
        REM Create package directories
        for %%d in ("%class_path:\=" "%") do (
            if not exist "%override_dir%\java\%%~d" mkdir "%override_dir%\java\%%~d"
        )
        
        REM Copy existing file if it exists
        if exist "%PROJECT_DIR%\src\main\java\%package_path%" (
            copy "%PROJECT_DIR%\src\main\java\%package_path%" "!target_file!"
            echo Copied existing file to override location
        ) else (
            echo Auto-generating new class override
            echo Placeholder implementation - please edit manually
        )
    ) else (
        echo Override file already exists: !target_file!
    )
)

echo.
echo Override directory: %override_dir%
echo Target file: %target_file%
echo Version: %version%
echo.
echo Next steps:
echo 1. Edit the override file at: %target_file%
echo 2. Test with: gradlew.bat runClient
echo 3. Build with: gradlew.bat build

endlocal